# general configuration
url: https://samcunliffe.me 
#https://samcunliffe.github.io
baseurl: ''

# compass configuration
compass:
  logo: "/images/brassai.png"
  author: "Sam Cunliffe"
  tagline: "flavour physics / heavy metal / pizza"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
#relative_permalinks: true
